name: Stubs code validation

on:
    pull_request:
    push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions:
            - "7.4"
            - "8.0"
            - "8.1"
            - "8.2"
            - "8.3"
            - "8.4"

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, dom, zip, psr

    - name: Get Composer Cache Directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: "Install development dependencies with Composer"
      uses: "ramsey/composer-install@v3"
      with:
        composer-options: "--prefer-dist"

    - name: run psalm
      if: always()
      run: vendor/bin/psalm

    - name: run phpcs
      if: always()
      run: vendor/bin/phpcs
